### PR TITLE
Fix Eager Conflict Resolution Deadlock and Improve Mutable Store Code Quality

### LINKED ISSUE #578: [BUG] Deadlock during synchronization in MutableStore
Reproduce:
1. Make unsuccessful write to store. 
In other words call store.write.
UpdaterResult returned by post function in Updater should be something like UpdaterResult.Error.Exception(Exception(""))
2. Adjust Api so that post function in Updater will return UpdaterResult.Success in next calls.
3. Read data from store
In other words call store.stream. 

Result:
No data will come to flow because deadlock happened during synchronization.

Cause of bug:
Function tryEagerlyResolveConflicts is called in RealMutableStore. 
withThreadSafety is called in first line of the function. It calls storeLock.lock() for the first time.
updateWriteRequestQueue is called in the block of withThreadSafety.
Function withWriteRequestQueueLock is called in updateWriteRequestQueue.
withThreadSafety is called in withWriteRequestQueueLock.
 It calls storeLock.lock() for the second time in the same thread that causes deadlock.

Example app. Store is used in com/example/dropboxstore/ui/screens/store/StoreViewModel.kt
[Store-deadlock.zip](https://github.com/MobileNativeFoundation/Store/files/12735552/Store-deadlock.zip)

### LINKED ISSUE #667: [BUG] Deadlock in tryEagerlyResolveConflicts
**Describe the bug**
Deadlock caused by trying to capture lock on storeLock in tryEagerlyResolveConflicts in RealMutableStore.kt.

**To Reproduce**
- Reach to a state, when store need to resolve conflicts and push data to remote.

**Expected behavior**
- No Deadlock.

**See Below Screenshot**
image

@matt-ramotar 
Reference: https://kotlinlang.slack.com/archives/C06007Z01HU/p1729276957911359

### PR DESCRIPTION
**Pull request by matt-ramotar**
Closes #667
Closes #578

This PR is fixing a deadlock in eager conflict resolution. To improve code quality, this PR also:

- Expands on RealMutableStore documentation
- Extracts logging into an internal interface and provides a default implementation to the RealMutableStore
- Introduces internal test utility classes
- Adds RealMutableStore unit tests

### CODE REVIEW

**Comment by digitalbuddha** [comment]
nit, can we try to keep the prs single purpose for easier review <3

File: store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Logger.kt [hunk 1]
```diff
@@ -0,0 +1,24 @@
+package org.mobilenativefoundation.store.store5
+
+/**
+ * A simple logging interface for logging error and debug messages.
+ */
+interface Logger {
```
Comment (digitalbuddha) [inline store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Logger.kt:6]: nice!

File: store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Logger.kt [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+        throwable: Throwable? = null,
+    )
+
+    /**
+     * Logs a debug message.
+     *
+     * @param message The debug message to log.
+     */
+    fun debug(message: String)
+}
```
Comment (digitalbuddha) [inline store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Logger.kt:24]: no info?

**Review by digitalbuddha — APPROVED** [review]
thank you for adding tests <3

File: store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Logger.kt (hunk 2 above)
Comment (matt-ramotar) [reply store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/Logger.kt:24]: We're not currently using info and this component isn't currently being exposed to the consumer. There's an open request to improve logging #638. My plan is to replace this then with logging hooks delegated to the user
